// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadMinimaltrace returns the embedded CollectionSpec for Minimaltrace.
func LoadMinimaltrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MinimaltraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Minimaltrace: %w", err)
	}

	return spec, err
}

// LoadMinimaltraceObjects loads Minimaltrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MinimaltraceObjects
//	*MinimaltracePrograms
//	*MinimaltraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMinimaltraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMinimaltrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MinimaltraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MinimaltraceSpecs struct {
	MinimaltraceProgramSpecs
	MinimaltraceMapSpecs
	MinimaltraceVariableSpecs
}

// MinimaltraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MinimaltraceProgramSpecs struct {
	DetectExecve *ebpf.ProgramSpec `ebpf:"detect_execve"`
}

// MinimaltraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MinimaltraceMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// MinimaltraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MinimaltraceVariableSpecs struct {
}

// MinimaltraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type MinimaltraceObjects struct {
	MinimaltracePrograms
	MinimaltraceMaps
	MinimaltraceVariables
}

func (o *MinimaltraceObjects) Close() error {
	return _MinimaltraceClose(
		&o.MinimaltracePrograms,
		&o.MinimaltraceMaps,
	)
}

// MinimaltraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type MinimaltraceMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *MinimaltraceMaps) Close() error {
	return _MinimaltraceClose(
		m.Events,
	)
}

// MinimaltraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type MinimaltraceVariables struct {
}

// MinimaltracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type MinimaltracePrograms struct {
	DetectExecve *ebpf.Program `ebpf:"detect_execve"`
}

func (p *MinimaltracePrograms) Close() error {
	return _MinimaltraceClose(
		p.DetectExecve,
	)
}

func _MinimaltraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed minimaltrace_bpfel.o
var _MinimaltraceBytes []byte
