// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMinimaltrace returns the embedded CollectionSpec for minimaltrace.
func loadMinimaltrace() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MinimaltraceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load minimaltrace: %w", err)
	}

	return spec, err
}

// loadMinimaltraceObjects loads minimaltrace and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*minimaltraceObjects
//	*minimaltracePrograms
//	*minimaltraceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMinimaltraceObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMinimaltrace()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// minimaltraceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type minimaltraceSpecs struct {
	minimaltraceProgramSpecs
	minimaltraceMapSpecs
	minimaltraceVariableSpecs
}

// minimaltraceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type minimaltraceProgramSpecs struct {
	DetectExecve *ebpf.ProgramSpec `ebpf:"detect_execve"`
}

// minimaltraceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type minimaltraceMapSpecs struct {
}

// minimaltraceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type minimaltraceVariableSpecs struct {
}

// minimaltraceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type minimaltraceObjects struct {
	minimaltracePrograms
	minimaltraceMaps
	minimaltraceVariables
}

func (o *minimaltraceObjects) Close() error {
	return _MinimaltraceClose(
		&o.minimaltracePrograms,
		&o.minimaltraceMaps,
	)
}

// minimaltraceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type minimaltraceMaps struct {
}

func (m *minimaltraceMaps) Close() error {
	return _MinimaltraceClose()
}

// minimaltraceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type minimaltraceVariables struct {
}

// minimaltracePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMinimaltraceObjects or ebpf.CollectionSpec.LoadAndAssign.
type minimaltracePrograms struct {
	DetectExecve *ebpf.Program `ebpf:"detect_execve"`
}

func (p *minimaltracePrograms) Close() error {
	return _MinimaltraceClose(
		p.DetectExecve,
	)
}

func _MinimaltraceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed minimaltrace_bpfel.o
var _MinimaltraceBytes []byte
