// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type AtareeProcInfo struct {
	_    structs.HostLayout
	Ppid uint32
}

// LoadAtaree returns the embedded CollectionSpec for Ataree.
func LoadAtaree() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AtareeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Ataree: %w", err)
	}

	return spec, err
}

// LoadAtareeObjects loads Ataree and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AtareeObjects
//	*AtareePrograms
//	*AtareeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAtareeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAtaree()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AtareeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AtareeSpecs struct {
	AtareeProgramSpecs
	AtareeMapSpecs
	AtareeVariableSpecs
}

// AtareeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AtareeProgramSpecs struct {
	HandleExit *ebpf.ProgramSpec `ebpf:"handle_exit"`
	HandleFork *ebpf.ProgramSpec `ebpf:"handle_fork"`
	OnMmap     *ebpf.ProgramSpec `ebpf:"on_mmap"`
	OnMprotect *ebpf.ProgramSpec `ebpf:"on_mprotect"`
	OnOpenat   *ebpf.ProgramSpec `ebpf:"on_openat"`
	OnPtrace   *ebpf.ProgramSpec `ebpf:"on_ptrace"`
}

// AtareeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AtareeMapSpecs struct {
	ProcessTree *ebpf.MapSpec `ebpf:"process_tree"`
	Rb          *ebpf.MapSpec `ebpf:"rb"`
}

// AtareeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AtareeVariableSpecs struct {
}

// AtareeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAtareeObjects or ebpf.CollectionSpec.LoadAndAssign.
type AtareeObjects struct {
	AtareePrograms
	AtareeMaps
	AtareeVariables
}

func (o *AtareeObjects) Close() error {
	return _AtareeClose(
		&o.AtareePrograms,
		&o.AtareeMaps,
	)
}

// AtareeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAtareeObjects or ebpf.CollectionSpec.LoadAndAssign.
type AtareeMaps struct {
	ProcessTree *ebpf.Map `ebpf:"process_tree"`
	Rb          *ebpf.Map `ebpf:"rb"`
}

func (m *AtareeMaps) Close() error {
	return _AtareeClose(
		m.ProcessTree,
		m.Rb,
	)
}

// AtareeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadAtareeObjects or ebpf.CollectionSpec.LoadAndAssign.
type AtareeVariables struct {
}

// AtareePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAtareeObjects or ebpf.CollectionSpec.LoadAndAssign.
type AtareePrograms struct {
	HandleExit *ebpf.Program `ebpf:"handle_exit"`
	HandleFork *ebpf.Program `ebpf:"handle_fork"`
	OnMmap     *ebpf.Program `ebpf:"on_mmap"`
	OnMprotect *ebpf.Program `ebpf:"on_mprotect"`
	OnOpenat   *ebpf.Program `ebpf:"on_openat"`
	OnPtrace   *ebpf.Program `ebpf:"on_ptrace"`
}

func (p *AtareePrograms) Close() error {
	return _AtareeClose(
		p.HandleExit,
		p.HandleFork,
		p.OnMmap,
		p.OnMprotect,
		p.OnOpenat,
		p.OnPtrace,
	)
}

func _AtareeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ataree_bpfeb.o
var _AtareeBytes []byte
